apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: echo-kem
spec:
  environments:
    - name: development
      build:
        from: master
    - name: qa
      build:
        from: release/*
    - name: prod
  components:
    - name: www
      src: ./www
      publicPort: http
      ports:
       - name: http
         port: 3000
      environmentConfig:
        - environment: development
          monitoring: false
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
            limits:
              memory: "54Mi"
              cpu: "20m"
          replicas: 2
    - name: echo
      src: ./echo
      publicPort: http
      ports:
       - name: http
         port: 3001
      environmentConfig:
        - environment: development
          monitoring: true
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
            limits:
              memory: "54Mi"
              cpu: "20m"
          replicas: 2
  dnsAppAlias:
    environment: development
    component: www
